<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Positions Needed</name>
   <tag></tag>
   <elementGuidId>909e5245-2f03-45d4-8c63-df9a0c8eb191</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ui-id-3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d836b774-b095-48cd-aeb9-84d0d9f3e983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#group-1456436124.683</value>
      <webElementGuid>9d82ef62-63cf-4010-9e64-f7318f5659ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>9e69ccf7-935f-4d42-a3b7-1db509025de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-tabs-anchor</value>
      <webElementGuid>cafc042e-e6df-4e89-8ed7-217c22263a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-3</value>
      <webElementGuid>2fb9fbf9-3768-440c-b000-f9f742466cfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Positions Needed</value>
      <webElementGuid>c31d7d23-d19e-4b87-8413-ef85b782479b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-3&quot;)</value>
      <webElementGuid>61ad566a-1087-4761-a64b-39b78c17ac1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ui-id-3']</value>
      <webElementGuid>10dbbba9-771d-496c-83eb-7b0c5bf8c3a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabs']/ul/li[3]/a</value>
      <webElementGuid>045c94bd-2217-4814-974e-bffe62acd5e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Positions Needed')]</value>
      <webElementGuid>2425f1bd-643e-4eca-af9a-0548f6c104ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='School Info'])[1]/following::a[1]</value>
      <webElementGuid>c53def08-4138-4ecd-8ed0-9c40c8d9c22b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Info'])[1]/following::a[2]</value>
      <webElementGuid>8ea5508e-658a-48c6-bedd-c8b0dc3aa144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service Options'])[1]/preceding::a[1]</value>
      <webElementGuid>255f2324-721d-4242-a70c-817d37d8e8b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Readiness'])[1]/preceding::a[2]</value>
      <webElementGuid>65925d53-fcec-4673-a772-b129336db6f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Positions Needed']/parent::*</value>
      <webElementGuid>6eb5c1e4-4fef-4549-aa4e-ec7e1c21deb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#group-1456436124.683')]</value>
      <webElementGuid>f3a97228-c24d-478b-b933-f06658f70ea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[3]/a</value>
      <webElementGuid>bb55db47-15be-4566-b063-52920dfda983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#group-1456436124.683' and @id = 'ui-id-3' and (text() = 'Positions Needed' or . = 'Positions Needed')]</value>
      <webElementGuid>245ee4d1-bdf4-429e-8686-3bede0fb970c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
