<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Screenshots</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>372d8645-ce8b-4f48-b47f-e210fc16c9e9</testSuiteGuid>
   <testCaseLink>
      <guid>cd356634-e58a-464d-a595-2249b594ea3f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Screenshots/Screenshot Journey Partner</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20fc5f53-11a0-4380-83d4-375d48a45d3a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>025be486-5b6e-445c-8409-7f34961ae2b5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4cdd8aa9-f012-4a21-ba04-7cb968a84a84</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Screenshots/Screenshot Education Candidate</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0587f44a-426c-4606-b81b-8f376f92e3bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>08bc0d4c-1019-469c-a467-118bad8042cf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>088a0f0a-a807-43ad-a321-43218f739e6b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Screenshots/Screenshot Education Partner</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b11b1e19-02c1-43f2-8cfd-a113a5df9b2d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e491591f-a625-4f31-947f-d8f98ee0c7c7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bbe4e86f-f89b-4137-ad0a-30814929b0e5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Screenshots/Screenshot Journey Candidate</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09ba0cf9-35c9-4d3e-b540-d2b8ed100d1d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>286e12de-9b7e-428f-8932-7e6c6d7b7449</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0838ca40-b3ed-424c-9c47-c01d9cc43246</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Screenshots/Screenshot Journey Guide</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e5f708e-8f42-435d-8043-bc48f67bc925</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b3a2dc2-a170-4d1e-a83c-af8b40d91f45</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0ba05cc1-d742-4add-878a-a10b1756286f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Screenshots/Screenshot Quickstart</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>728d8c65-c719-44e7-ba66-4dba0023459d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e23e8925-1c34-488b-b79f-0af2153a7114</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
