<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Need Candidates for Short-Term Assignments</name>
   <tag></tag>
   <elementGuidId>2b8ed5b0-ecaf-43aa-bea4-295605c96daa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='profile_group-1446521622.636_need_positions_in_short-term_specifically']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>64a7ce05-1005-4a8a-a152-b79db4ec6d7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dependant</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3309181d-063a-4b9c-a6da-515771476d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>need_positions_in_short-term_specifically</value>
      <webElementGuid>c1443760-7095-4378-9373-8ec0c8936fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>174</value>
      <webElementGuid>9aa3cf33-0f24-4966-87f8-f0bd52ef4b3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1446521622.636][need_positions_in_short-term_specifically]</value>
      <webElementGuid>2bbdad12-e7af-433d-9bcd-2e9ea133d926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1446521622.636_need_positions_in_short-term_specifically</value>
      <webElementGuid>00fb9a7f-5785-40ad-97a5-97f950439932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>da5b3b96-014a-4f40-9c82-22b98deb08bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>10cc9488-0bac-4440-8060-58cde38ebb91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>2fb9a671-5104-4606-9d93-4206e446d65f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_group-1446521622.636_need_positions_in_short-term_specifically&quot;)</value>
      <webElementGuid>2dbaecaa-1bb7-4b16-a05d-d6f254e09080</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='profile_group-1446521622.636_need_positions_in_short-term_specifically']</value>
      <webElementGuid>7477ca54-8e8b-4748-8e7b-53d104a87645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1446521622.636']/div[9]/div[2]/input[2]</value>
      <webElementGuid>6393ab84-9843-43f7-964a-b67c398607c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/input[2]</value>
      <webElementGuid>243d3428-2d87-4b2b-aebf-759a662b91b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'profile[group-1446521622.636][need_positions_in_short-term_specifically]' and @id = 'profile_group-1446521622.636_need_positions_in_short-term_specifically' and @type = 'checkbox' and @checked = 'checked']</value>
      <webElementGuid>db95d76a-9027-49aa-9709-5ef8915952e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
