<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_Need to See Specific IT Jobs</name>
   <tag></tag>
   <elementGuidId>5660a173-e04e-48a4-ac1d-7457b59d2d47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;job_group1_need_specific_it_jobs?&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fa2f74e9-4722-4d7c-9597-e88f1c59e31c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dependant</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>dc1f232f-19f2-4cb8-9b8d-8086f951a26e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>need_specific_it_jobs?</value>
      <webElementGuid>039881c9-ec93-43b5-805d-4d295e58a571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>154</value>
      <webElementGuid>dfd3c790-195f-49cc-83b8-d89dba7f8cfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>job[group1][need_specific_it_jobs?]</value>
      <webElementGuid>24a2a10f-463d-479f-a425-aae261e95b26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>job_group1_need_specific_it_jobs?</value>
      <webElementGuid>d93f14d0-bc8b-47c2-9bd4-f241fc6c46de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>45a39a83-883d-40ef-97e6-d141361831e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>bd69c753-aaae-47d3-9fe3-95761d297838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-form-interact-field-id</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bdbbb38f-e50d-4bb8-9afb-dd353f800a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;job_group1_need_specific_it_jobs?&quot;)</value>
      <webElementGuid>b53a6bf8-55f6-49fe-a45f-10c0d093c323</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='job_group1_need_specific_it_jobs?']</value>
      <webElementGuid>62e8d03c-3dd6-4c50-a1ee-fc911a9e6067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group1']/div[21]/div[2]/input[2]</value>
      <webElementGuid>01a518e2-b5b0-4fdb-9135-d186c2342657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input[2]</value>
      <webElementGuid>0c0c0228-0697-44e6-ad79-2ed6be718858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'job[group1][need_specific_it_jobs?]' and @id = 'job_group1_need_specific_it_jobs?' and @type = 'checkbox']</value>
      <webElementGuid>78de1e09-b651-455f-9bbb-260132de8763</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
