<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Spouse Teaching Prefs</name>
   <tag></tag>
   <elementGuidId>ba12b489-2f5c-4472-8b45-1fe49374200c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ui-id-12']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-12</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>66981558-0afa-4e7a-9647-4a9c06927d96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#group-1631421746.766</value>
      <webElementGuid>92850b34-67c1-4d5d-8819-0b52c59aa1ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dependent-group ui-tabs-anchor</value>
      <webElementGuid>0dd57726-a961-458d-8a44-f529b09a07e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>group-1631421746.766</value>
      <webElementGuid>5e731ee2-a9f6-4eab-b063-50c61c200871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-depends-on</name>
      <type>Main</type>
      <value>spouse_an_educator</value>
      <webElementGuid>f70c67a7-19e1-4202-8b57-35391629a02a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>077b08b4-4e8f-49d4-ae4a-9b0256ba4844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-12</value>
      <webElementGuid>7645327b-35d8-4f40-95cf-96ec9571578b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Spouse Teaching Prefs</value>
      <webElementGuid>be4b75de-6c6f-461c-b71f-b4c35034bbd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-12&quot;)</value>
      <webElementGuid>808cbac7-9ac3-4125-9b50-31e08146be62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ui-id-12']</value>
      <webElementGuid>bfcf008c-6fd3-4b94-b16f-24f7baf73a3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabs']/ul/li[12]/a</value>
      <webElementGuid>b69140f8-e9bf-4707-b10a-9d7f5185576c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Spouse Teaching Prefs')]</value>
      <webElementGuid>832a1096-98e3-4e5f-9c60-ce415d83c86e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spouse Education'])[1]/following::a[1]</value>
      <webElementGuid>f7e98d3f-d694-4e19-92e5-ba60058c0e6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spouse Service Prefs'])[1]/following::a[2]</value>
      <webElementGuid>a9e733ec-0273-40ed-a94f-069e210b78e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name*'])[1]/preceding::a[1]</value>
      <webElementGuid>9421335f-7a39-4e36-9125-8a7d6a4dcbaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name*'])[1]/preceding::a[1]</value>
      <webElementGuid>bf824cff-72d2-43ad-98c5-33f86072a0b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Spouse Teaching Prefs']/parent::*</value>
      <webElementGuid>b336f9d2-eb63-4a7d-8d02-c0bd244e1f4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#group-1631421746.766')]</value>
      <webElementGuid>237952e2-987d-4701-9a17-ea19b5a67d85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[12]/a</value>
      <webElementGuid>3a3dbb25-a83c-4188-b418-a529aefeab7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#group-1631421746.766' and @id = 'ui-id-12' and (text() = 'Spouse Teaching Prefs' or . = 'Spouse Teaching Prefs')]</value>
      <webElementGuid>8e50df8e-4783-4070-ab2b-150184f5242f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
