<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Spouse Experience</name>
   <tag></tag>
   <elementGuidId>6555b69b-16b4-42c3-8683-cebc3ad00fc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ui-id-9']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>62214f2e-fa90-4142-8e41-36a7257f1f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#group-1631402760.799</value>
      <webElementGuid>8ff3a4f6-524f-4ce3-929a-70743474a2b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dependent-group ui-tabs-anchor</value>
      <webElementGuid>62e26f08-a97d-4702-bdf7-98444ac9edb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>group-1631402760.799</value>
      <webElementGuid>c21eb0a3-cdb6-429c-b2b0-23d29ea5fa4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-depends-on</name>
      <type>Main</type>
      <value>spouse_serving_with_you?</value>
      <webElementGuid>71d1e36d-dfae-4198-b9cc-0e7543cc6e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e0d1c351-0b37-402c-865c-67f335fdbb89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-9</value>
      <webElementGuid>c96f8a47-3707-4905-b9c8-d45af0de8956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Spouse Experience</value>
      <webElementGuid>5a2982ba-4fae-4550-b09b-13d9e5cc0ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-9&quot;)</value>
      <webElementGuid>38e96ca9-e060-4e23-9d99-13750cd2973d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ui-id-9']</value>
      <webElementGuid>40b41223-7f22-4662-ae8f-3c1bc2546df2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabs']/ul/li[9]/a</value>
      <webElementGuid>7958cc4d-9fd4-45c6-9f1d-f8bc8a7812ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Spouse Experience')]</value>
      <webElementGuid>8011f56c-cf3b-44fe-b2d4-c07cec9b9838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spouse Info'])[1]/following::a[1]</value>
      <webElementGuid>104cf631-7744-48ea-9215-4b9969cc070e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Options/Comment'])[1]/following::a[2]</value>
      <webElementGuid>43cf477b-7ddb-4134-a9d3-808cdd4783d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spouse Service Prefs'])[1]/preceding::a[1]</value>
      <webElementGuid>31de49ff-d595-4b69-9fc9-56858236cf35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spouse Education'])[1]/preceding::a[2]</value>
      <webElementGuid>be864ab9-3e7e-4616-a9eb-8c55d9b37411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Spouse Experience']/parent::*</value>
      <webElementGuid>09090c75-c6f0-4559-b783-67c02a0c57c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#group-1631402760.799')]</value>
      <webElementGuid>69d7d2b7-9a75-4af4-8bb5-4a8d8a2a1228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[9]/a</value>
      <webElementGuid>a106b68f-9022-4d26-82ff-22e43a58039d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#group-1631402760.799' and @id = 'ui-id-9' and (text() = 'Spouse Experience' or . = 'Spouse Experience')]</value>
      <webElementGuid>771c488b-6a03-4f9a-b471-cb6b01645534</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
