<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Spouse Info</name>
   <tag></tag>
   <elementGuidId>10414e20-638b-4e53-91b0-8902a479f679</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ui-id-8']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f9165eb6-347f-4c64-9e2d-7f2d9b424385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#group-1463520836.272</value>
      <webElementGuid>adda65f1-a131-4dfa-bb72-e57e4c1ba7ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dependent-group ui-tabs-anchor</value>
      <webElementGuid>751ebce4-2ac5-4487-8c75-7f83a189a2f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>group-1463520836.272</value>
      <webElementGuid>9b2cb8ae-8aa6-472f-b5fb-b5dd2b7ecbd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-depends-on</name>
      <type>Main</type>
      <value>marital_status</value>
      <webElementGuid>592dd9b6-fa67-404b-ac20-4d3ff6a20591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>275395c4-8950-4546-8ec1-ac9e4c142667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-8</value>
      <webElementGuid>ce12ac26-36c7-4d97-a0b8-a4ba88468b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Spouse Info</value>
      <webElementGuid>0678751f-cd20-4c7b-abf2-df2d73076ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-8&quot;)</value>
      <webElementGuid>3941b89e-43a8-4443-a296-e1a9d7421da9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ui-id-8']</value>
      <webElementGuid>b40c3e7d-8808-4c83-b8ed-3623f8c3372f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabs']/ul/li[8]/a</value>
      <webElementGuid>8ca9f991-49cd-4bea-af44-46f11f2a6fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Spouse Info')]</value>
      <webElementGuid>36d1037c-aaa9-4a41-ad57-4a793f41b289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Options/Comment'])[1]/following::a[1]</value>
      <webElementGuid>81202113-ff63-43f2-ae5a-b151fd69e658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preferences'])[1]/following::a[2]</value>
      <webElementGuid>947f3648-a3d2-4d4c-b26e-3aa6696de44d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spouse Experience'])[1]/preceding::a[1]</value>
      <webElementGuid>4a9e5c70-8bee-41d7-9e83-5706f4c06021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spouse Service Prefs'])[1]/preceding::a[2]</value>
      <webElementGuid>8cb47fb1-655d-4f85-9f50-45f6282c029b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Spouse Info']/parent::*</value>
      <webElementGuid>deba08f2-bf74-4c0d-b598-ccad6149453b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#group-1463520836.272')]</value>
      <webElementGuid>4ef7b385-a70d-4cd4-824b-b25d0234e264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[8]/a</value>
      <webElementGuid>ff06496a-f14f-497b-9421-c88ddfb19dad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#group-1463520836.272' and @id = 'ui-id-8' and (text() = 'Spouse Info' or . = 'Spouse Info')]</value>
      <webElementGuid>eb39d6ec-9b00-4780-9f38-2e8feaa188ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
