<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Marital Status</name>
   <tag></tag>
   <elementGuidId>9170c012-4407-4ca0-a933-9fc69a18d60b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='profile_group-1443546232.861_marital_status']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>12ed1e74-dff0-49ee-b5ed-0739d218ed01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dependant</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0d11d0a1-78b3-4fae-8e38-6d24a6904a82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>marital_status</value>
      <webElementGuid>46c3c84a-4a26-43a7-b71e-82fd84dee81d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>221</value>
      <webElementGuid>3ee3e958-6fc3-4a86-866f-4b4ae81816ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1443546232.861][marital_status]</value>
      <webElementGuid>7804152d-a58f-4deb-9f56-8e16b0b3c7cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1443546232.861_marital_status</value>
      <webElementGuid>298e203a-65ef-45fc-a2f0-3508e6c1d05b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>custom-field</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>5658e47f-f297-4916-864c-80a06338d8a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-form-interact-field-id</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>6653aac8-afce-4adf-91e9-3fcfb26d9ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Single
Married
Separated
Divorced
Widowed
</value>
      <webElementGuid>5d0d43b8-bcdf-49c1-9f36-4887fddc4c90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_group-1443546232.861_marital_status&quot;)</value>
      <webElementGuid>edf0512c-d3ab-4d45-84e4-378d52a84bf8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='profile_group-1443546232.861_marital_status']</value>
      <webElementGuid>0c785f00-ce46-4bd3-9f19-420d24840ccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1443546232.861']/div[15]/div[2]/select</value>
      <webElementGuid>03094f3d-3663-4b6f-b014-51d07aeecdc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marital status'])[1]/following::select[1]</value>
      <webElementGuid>ff995e0a-ce06-4703-a62e-32f3e58efeb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The birth year field is required.'])[1]/following::select[1]</value>
      <webElementGuid>2e37b377-d90d-49b5-8b1d-56b9c96d1de7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dependent Children'])[1]/preceding::select[1]</value>
      <webElementGuid>d758492f-2c80-4ace-aa4e-333fc9d4c9dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check to Agree with Terms and Conditions to continue'])[1]/preceding::select[2]</value>
      <webElementGuid>d0c2938f-694c-4e06-8696-6bf5c4816c59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div[2]/select</value>
      <webElementGuid>8628c64d-4cd3-404d-a9ad-b45cadb67314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'profile[group-1443546232.861][marital_status]' and @id = 'profile_group-1443546232.861_marital_status' and (text() = '
Single
Married
Separated
Divorced
Widowed
' or . = '
Single
Married
Separated
Divorced
Widowed
')]</value>
      <webElementGuid>9e3a3b6d-b441-4a22-a65c-62a3ed569e7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
