<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Spouse Info</name>
   <tag></tag>
   <elementGuidId>36cd8b7f-f60e-4658-9bfc-161077ded34c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ui-id-8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ui-id-8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>de726d9c-781a-474f-b3f9-5a8e9f0dde71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#group-1623987729.611</value>
      <webElementGuid>d620612b-17a6-4739-bc93-f2088c71f0a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dependent-group ui-tabs-anchor</value>
      <webElementGuid>34d1ee91-10ce-4de7-8615-a0c6a83822f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>group-1623987729.611</value>
      <webElementGuid>9d5dd4f9-9e9f-43cb-9c4c-a3eebae516bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-depends-on</name>
      <type>Main</type>
      <value>marital_status</value>
      <webElementGuid>67818d77-8674-4ac9-88f9-8bb710b52dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>0fa1dbcf-0788-464f-99a8-96421708b80d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-8</value>
      <webElementGuid>ae604591-4b36-4173-81d8-80272aed408f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Spouse Info</value>
      <webElementGuid>64096bf7-4017-41f3-9525-0b2a3ffc2add</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-8&quot;)</value>
      <webElementGuid>e9aab605-ed80-4e64-9ced-d02fca460e46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ui-id-8']</value>
      <webElementGuid>8c7d29db-2a24-4cc5-a4a6-1a55eba05647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabs']/ul/li[8]/a</value>
      <webElementGuid>173dbdfa-d16e-4054-8fb8-ae60321d8045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Spouse Info')]</value>
      <webElementGuid>96b32e95-e0ff-43e8-89f7-9a2c964d65f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IT Skills and Interest'])[1]/following::a[1]</value>
      <webElementGuid>e0dcdcbc-2974-4c20-85a5-464f0b5796dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Ministry Prefs'])[1]/following::a[2]</value>
      <webElementGuid>2ab6f446-40b7-45e1-b555-ec9b63c60924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spouse Experience'])[1]/preceding::a[1]</value>
      <webElementGuid>fccbb8a9-c25a-4d6b-970d-26df3e063a17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spouse Ministry Prefs'])[1]/preceding::a[2]</value>
      <webElementGuid>84d818bb-671f-4527-944b-f2b44f42644a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Spouse Info']/parent::*</value>
      <webElementGuid>483602b0-b5a6-45d6-af44-989055acffec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#group-1623987729.611')]</value>
      <webElementGuid>212363e9-5008-4db2-9324-d5d636a15a11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[8]/a</value>
      <webElementGuid>cf3f0da0-d89c-4ba6-8c5a-f75d648119a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#group-1623987729.611' and @id = 'ui-id-8' and (text() = 'Spouse Info' or . = 'Spouse Info')]</value>
      <webElementGuid>049f2012-ba9d-4249-8f29-3acef2b754a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
