<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Spouse Serving with You Yes</name>
   <tag></tag>
   <elementGuidId>e4803f62-ecd5-4851-b989-ccf43b37a710</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='profile[group-1623987729.611][spouse_serving_with_you?]'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1d0d4581-5ca1-4243-8ae7-58f8a9640218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>8f5080e4-98c3-4129-9cf7-48494e79cb75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>custom-field</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a0c28978-de5d-425e-a03b-75d9c6722344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dependant</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>070ff340-85ee-4d8f-a681-2dde27bb6654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>spouse_serving_with_you?</value>
      <webElementGuid>a315c3c8-56ad-4c95-bacb-ebf987ab2c6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>227</value>
      <webElementGuid>1708e903-fa44-4719-b361-651bfc1d1a94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1623987729.611][spouse_serving_with_you?]</value>
      <webElementGuid>fcdf5c73-bf85-4ceb-b6f0-fe9ebe13f43a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>8a2e3114-09c1-4dde-b6c7-dab46ccbb12b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1623987729.611&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[1]/input[2]</value>
      <webElementGuid>0f79f852-3d79-4e4d-ae77-9ad61ee42be4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='profile[group-1623987729.611][spouse_serving_with_you?]'])[2]</value>
      <webElementGuid>e704e6f2-492d-40e9-8121-14730531d549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1623987729.611']/div[6]/div[3]/div/input[2]</value>
      <webElementGuid>d56ddd1e-2b52-4d4e-a2d7-e87a3bad9728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input[2]</value>
      <webElementGuid>bdc0fd8c-5b37-4143-b4d1-e24fb91a61a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'profile[group-1623987729.611][spouse_serving_with_you?]']</value>
      <webElementGuid>0b1f8dac-8a6b-4c4e-83e9-dde2d540b85a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
